### ISSUE TITLE
[Feature Request] Side lights 

### ISSUE THREAD

**Issue by hugows** [jincao1/qmk_firmware#3]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

Is it possible to play with the sidelights or that is not in this firmware?
Would be awesome to have them responding to typing speed over the last 10 keys (or last second) like a level!

**Comment by jincao1** [comment]
@hugows - the intent of this firmware is mainly for personal benefits as the NuPhy stock firmware was not very stable. I'm choosing to keep things quite vanilla as is since I just need a stable keyboard. I don't even use the LEDs myself but you're more than welcome to fork the code and implement this! It should be something that can be done relatively easily and you can reference how the stock QMK animations pertaining to WPM and speed is implemented.
